### ISSUE TITLE
Failed to analyze repository

### ISSUE THREAD

**Issue by hoijui** [deps-rs/deps.rs#210] opened 2023-12-04 06:52 UTC
See it here:
<https://deps.rs/repo/github/hoijui/projvar>

My guess is, that it is because of [this dependency line](
https://github.com/hoijui/projvar/blob/8dc3641749752c38b92459e9562402700b77d130/Cargo.toml#L49):

```toml
cli_utils = { version = "0.6", package = "cli_utils_hoijui" }
```

As it is probably the most unusual one.

Is it somehow possible to get to more info why the analysis failed?

**Comment by hoijui** [comment] 2023-12-04 19:55
Same happens with this crate, which has the same dependency line like the one above:
<https://deps.rs/repo/github/hoijui/repvar>

**Comment by szepeviktor** [comment] 2024-02-14 22:46
Seems like every repo fails: https://deps.rs/

**Comment by fluxxcode** [comment] 2024-02-14 22:54
> Seems like every repo fails: https://deps.rs/
> 
> @paolobarbolini Could you help?

I think this is a new bug. Yesterday or the day before yesterday everything was still working 🤔

**Comment by iganev** [comment] 2024-03-28 02:44
As of today all of my repositories report the same error at deps.rs

**Comment by hoijui** [comment] 2024-05-26 13:01
So since mid February (possibly months before that) this service is practically useless, and only four people care?
How can that be?

**Comment by robjtede** [comment] 2024-05-26 17:01
duplicate of #106

**Comment by robjtede** [comment] 2024-05-26 17:02
This is a known issue and the team have certain workarounds in place, clearly they're not good enough yet but we're working on it.

**Closed by robjtede** 2024-05-26 17:01 UTC
Labels: duplicate
