### ISSUE TITLE
Dependency checker is down

### ISSUE THREAD

**Issue by tobiasvl** [deps-rs/deps.rs#158] opened 2022-08-09 09:13 UTC
It seems that deps.rs doesn't check dependencies, and doesn't serve badges, like in #156.

**Comment by robjtede** [comment] 2022-08-09 09:49
dupe of #156

**Closed by robjtede** 2022-08-09 09:49 UTC
Labels: duplicate

**Comment by Feliix42** [comment] 2022-08-09 09:52
Indeed. We've had that problem in the last (see #156 for instance). Unfortunately, the issue only arises after the service has been up for a longer period of time. This could be caused by a number of problems, e.g. a memory leak, a very minor bug on our end or a lot of other stuff. 

A restart usually fixes the problem. Do we have any logs from the deployment server @cecton?

**Comment by kid** [comment] 2022-08-09 10:03
Logs can be seen here: https://argocd.kidibox.net/applications/deps-rs?node=%2FPod%2Fdeps-rs%2Fdeps-rs-prd-6b485cf97f-p68dc%2F0&tab=logs for anyone in the github organization

**Comment by kid** [comment] 2022-08-09 10:06
Seeing a lot of timeouts:
```
Aug 09 10:05:11.190 INFO time: 5000ms, status: 200 OK, path: /repo/github/nimiq/core-rs-albatross/status.svg
Aug 09 10:05:12.903 ERRO error: error sending request for url (https://raw.githubusercontent.com/mCaptcha/libmcaptcha/HE
AD/Cargo.toml): operation timed out, path: /repo/github/mCaptcha/libmcaptcha/status.svg
Aug 09 10:05:12.904 INFO time: 5002ms, status: 200 OK, path: /repo/github/mCaptcha/libmcaptcha/status.svg
Aug 09 10:05:14.339 ERRO error: error sending request for url (https://raw.githubusercontent.com/rgeometry/rgeometry/HEA
D/Cargo.toml): operation timed out, path: /repo/github/rgeometry/rgeometry/status.svg
Aug 09 10:05:14.340 INFO time: 5003ms, status: 200 OK, path: /repo/github/rgeometry/rgeometry/status.svg
Aug 09 10:05:14.991 ERRO error: error sending request for url (https://raw.githubusercontent.com/FyroxEngine/Fyrox/HEAD/
Cargo.toml): operation timed out, path: /repo/github/FyroxEngine/Fyrox/status.svg
Aug 09 10:05:14.991 INFO time: 5000ms, status: 200 OK, path: /repo/github/FyroxEngine/Fyrox/status.svg
Aug 09 10:05:18.728 ERRO error: error sending request for url (https://raw.githubusercontent.com/openbytedev/build-targe
t/HEAD/Cargo.toml): operation timed out, path: /repo/github/openbytedev/build-target/status.svg
Aug 09 10:05:18.728 INFO time: 5001ms, status: 200 OK, path: /repo/github/openbytedev/build-target/status.svg
Aug 09 10:05:19.222 INFO time: 0ms, status: 200 OK, path: /
Aug 09 10:05:21.222 ERRO error: error sending request for url (https://raw.githubusercontent.com/Equim-chan/Mortal/HEAD/
Cargo.toml): operation timed out, path: /repo/github/Equim-chan/Mortal/status.svg
Aug 09 10:05:21.222 INFO time: 5001ms, status: 200 OK, path: /repo/github/Equim-chan/Mortal/status.svg
Aug 09 10:05:26.677 ERRO error: error sending request for url (https://raw.githubusercontent.com/Equim-chan/Mortal/HEAD/
Cargo.toml): operation timed out, path: /repo/github/Equim-chan/Mortal/status.svg
Aug 09 10:05:26.678 INFO time: 5001ms, status: 200 OK, path: /repo/github/Equim-chan/Mortal/status.svg
Aug 09 10:05:29.222 INFO time: 0ms, status: 200 OK, path: /
Aug 09 10:05:32.653 ERRO error: error sending request for url (https://raw.githubusercontent.com/weihanglo/sfz/HEAD/Carg
o.toml): operation timed out, path: /repo/github/weihanglo/sfz/status.svg
Aug 09 10:05:32.654 INFO time: 5001ms, status: 200 OK, path: /repo/github/weihanglo/sfz/status.svg
Aug 09 10:05:33.643 ERRO error: error sending request for url (https://raw.githubusercontent.com/messense/robotparser-rs
/HEAD/Cargo.toml): operation timed out, path: /repo/github/messense/robotparser-rs/status.svg
Aug 09 10:05:33.643 INFO time: 5000ms, status: 200 OK, path: /repo/github/messense/robotparser-rs/status.svg
Aug 09 10:05:39.243 INFO time: 0ms, status: 200 OK, path: /
Aug 09 10:05:43.937 ERRO error: error sending request for url (https://raw.githubusercontent.com/Equim-chan/Mortal/HEAD/
Cargo.toml): operation timed out, path: /repo/github/Equim-chan/Mortal/status.svg
Aug 09 10:05:43.941 INFO time: 5008ms, status: 200 OK, path: /repo/github/Equim-chan/Mortal/status.svg
Aug 09 10:05:45.105 ERRO error: error sending request for url (https://raw.githubusercontent.com/EmbarkStudios/cargo-den
y/HEAD/Cargo.toml): operation timed out, path: /repo/github/EmbarkStudios/cargo-deny/status.svg
Aug 09 10:05:45.109 INFO time: 5006ms, status: 200 OK, path: /repo/github/EmbarkStudios/cargo-deny/status.svg
Aug 09 10:05:49.225 INFO time: 0ms, status: 200 OK, path: /
Aug 09 10:05:49.751 ERRO error: error sending request for url (https://raw.githubusercontent.com/exonum/exonum/HEAD/Carg
o.toml): operation timed out, path: /repo/github/exonum/exonum/status.svg
Aug 09 10:05:49.752 INFO time: 5002ms, status: 200 OK, path: /repo/github/exonum/exonum/status.svg
Aug 09 10:05:59.222 INFO time: 0ms, status: 200 OK, path: /
Aug 09 10:06:05.413 ERRO error: error sending request for url (https://raw.githubusercontent.com/webrtc-rs/media/HEAD/Ca
rgo.toml): operation timed out, path: /repo/github/webrtc-rs/media/status.svg
Aug 09 10:06:05.413 INFO time: 5000ms, status: 200 OK, path: /repo/github/webrtc-rs/media/status.svg
Aug 09 10:06:06.223 ERRO error: error sending request for url (https://gitlab.com/veloren/veloren/raw/HEAD/Cargo.toml):
operation timed out, path: /repo/gitlab/veloren/veloren/status.svg
Aug 09 10:06:06.224 INFO time: 5001ms, status: 200 OK, path: /repo/gitlab/veloren/veloren/status.svg
Aug 09 10:06:09.222 INFO time: 0ms, status: 200 OK, path: /
```

**Comment by cecton** [comment] 2022-08-09 10:25
lot of timeouts, maybe we're getting rate limited?
