### ISSUE TITLE
Site Not Showing Latest Versions

### ISSUE THREAD

**Issue by joshstoik1** [deps-rs/deps.rs#145] opened 2022-03-07 18:39 UTC
Hi there,

The deps.rs site doesn't seem to be picking up new package releases (or at least some of them). For example, [once_cell](https://deps.rs/crate/once_cell/) is coming up 1.9.0 rather than 1.10.0, and [deno](https://deps.rs/crate/deno/) is showing 1.19.0 instead of 1.19.2.

Maybe the server process needs a restart?

**Comment by paolobarbolini** [comment] 2022-03-07 18:41
It looks like #144 happened again. I'll send a PR bumping dependencies to see if that fixes it (and also to get the server to restart because of the new deployment)

**Comment by paolobarbolini** [comment] 2022-03-07 18:57
While waiting for CI to build and deploy I opened https://deps.rs/crate/poloto and it redirected to 5.19.1. I choose that crate because it happens to make a lot of releases. I guess the crates.io-index update process must have been broken for at least 10 days, since that's how old the next `poloto` version is.

That didn't last that long. Around that time we had already restarted the server because of #144

**Comment by joshstoik1** [comment] 2022-03-07 19:17
The restart seems to have done the trick. Thanks for taking care of that so quickly!

**Comment by joshstoik1** [comment] 2022-03-17 05:30
It looks like deps.rs has fallen out of sync again, but only within the past day or two. (It picked up [poloto 8.0.2](https://deps.rs/crate/poloto/8.0.2) from 3 days ago, but none of the subsequent releases published yesterday.)

I'm not sure if it's relevant, but I did notice a large backlog on the _docs_.rs build queue yesterday. Different site, obviously, but maybe there was a common logjam somewhere?

**Comment by paolobarbolini** [comment] 2022-03-18 13:22
I've made another dependencies bump PR (#147) just to have the deploy process restart the server again. I'll try setting up a server and leaving deps.rs running on it to see if I can reproduce it locally

**Comment by paolobarbolini** [comment] 2022-03-18 13:22
I'll leave this open though since I imagine it will happen again

**Comment by joshstoik1** [comment] 2022-04-19 20:18
@paolobarbolini Looks like it might be stuck again.

[swc_ecma_minifier](https://deps.rs/crate/swc_ecma_minifier/) `0.104.4` for example is about 2 days stale.

**Comment by paolobarbolini** [comment] 2022-04-22 14:40
Thanks for the report. #150 will get the server to restart again

**Comment by joshstoik1** [comment] 2022-05-16 03:57
Hi @paolobarbolini,

It's that time again. Haha. [rayon](https://deps.rs/crate/rayon/) is coming up `1.5.2` on deps.rs, but `1.5.3` was released a couple days ago.

**Comment by Feliix42** [comment] 2022-08-09 11:38
I am closing this to bundle discussions in #106.

**Closed by Feliix42** 2022-08-09 11:38 UTC
